Default: &defaults
  database: MovieServer.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: MovieServer_test.sqlite3
  <<: *defaults

Staging:
  database: MovieServer_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: MovieServer_production.sqlite3
  poolsize: 100
  <<: *defaults